FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml .
COPY dashboard ./dashboard
COPY src ./src

RUN pip install --upgrade pip
RUN pip install -e .
RUN pip install streamlit

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0"]
